import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderTop from "./components/HeaderTop";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      > 
      {/* Responsive for all device */}
        <div className="container mx-auto max-w-[1440px]">
       <HeaderTop />
        {children}
      
          </div>
      </body>
   
    </html>
  );
}
